sender.email=${EMAIL_USER}

sender.password=${EMAIL_PASS}

email.subject=QA Automation Engineer | Noida | 2 Yrs

resume.path=src/main/resources/resume/PiyushBaldaniya.pdf

excel.path=src/main/resources/RecruiterEmails.xlsx

email.template.path=src/main/resources/templates/email-template.html

